version: "3.9"

services:
  umbraco:
    image: codeforacause/#{UMBRACO_IMAGE_NAME}#:#{TAG_NUMBER}#
    container_name: "slobodanemacenu_umbraco"
    ports:
      - "#{UMBRACO_PORT}#:5113"
    environment:
      - ASPNETCORE_ENVIRONMENT=#{ASPNETCORE_ENVIRONMENT}#
      - ConnectionStrings__umbracoDbDSN=#{CONNECTION_STRING}#
    volumes:
      - ./data/uploads/:/app/uploads
      - ./data/wwwroot/uploads/:/app/wwwroot/uploads
      - ./data/media/:/app/wwwroot/media
    restart: always
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "slobodanemacenu_database"
    user: root
    ports:
      - "#{DATABASE_PORT}#:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=#{DATABASE_PASSWORD}#
    volumes:
      - slobodanemacenu_database_data:/var/opt/mssql/data
    restart: always
volumes:
  slobodanemacenu_database_data:
