version: "3.9"

services:
  umbraco:
    container_name: "slobodanemacenu_umbraco"
    build:
      context: ./Hakaton.SlobodaNemaCenu
      dockerfile: Dockerfile
    ports:
      - "${UMBRACO_PORT}:5113"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__umbracoDbDSN=${CONNECTION_STRING}
    volumes:
      - ./data/media/:/app/Media
      - ./data/uploads/:/app/uploads
      - ./data/wwwroot/uploads/:/app/wwwroot/uploads
    restart: always
    env_file:
      - .env
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "slobodanemacenu_database"
    user: root
    ports:
      - "${DATABASE_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - slobodanemacenu_database_data:/var/opt/mssql/data
    restart: always
    env_file:
      - .env
volumes:
  slobodanemacenu_database_data:
