name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["docker-compose.production.yaml"]'
        env:
          DATABASE_PORT: "${{ secrets.DATABASE_PORT }}"
          DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
      - name: Copy docker compose file via SSH password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "docker-compose.production.yaml"
          target: "~/Projects/slobodanemacenu/"
      - name: Starting docker compose file via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: docker compose -f ~/Projects/slobodanemacenu/docker-compose.production.yaml up --build -d
